setwd('/home/ronald/Documents/scripts/irace_benchmark/tuning')
library('irace')
scenario <- readScenario(filename = 'scenario.txt', scenario = defaultScenario())
checkIraceScenario(scenario = scenario)
irace.main(scenario = scenario)